name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM installs
        run: npm install --force
      - name: install postcss
        run: npm install rollup-plugin-postcss rollup-plugin-postcss-lit postcss
      - name: build src
        run: npm run build
      - name: code lint
        run: npm run lint
      - name: coverage
        run: npm run coverage
      - name: test coverage
          using: 'node12'
          main: 'checkCoverage.js'
      
      
        

